# Generated by Django 4.1.4 on 2022-12-15 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^0\\d{8,10}$')]),
        ),
    ]
